### ISSUE TITLE
Mobile Safari 8 and 9, sometimes throwing "Can't find variable: System"

### ISSUE THREAD

**Issue by tuurbo** [systemjs/systemjs#1103]
Version: SystemJS v0.19.9, systemjs-builder: 0.14.15, jspm: 0.16.19

I'm using getsentry to track my js errors and i'm no js pro, but it seems like the scripts aren't being executed in order. I'm unable to reproduce the errors myself with my iphone, I'm going off of what getsentry catches.

Error:
```undefined: ReferenceError: Can't find variable: System```

Here's hows my scripts are loaded:
```
// contains system-csp-production.js
<script src="/build/systemjs.js"></script>
// contains config.js
<script src="/build/config.js"></script>
// contains vendor scripts
<script src="/build/store-shared-bundle.js"></script>
// contains app script
<script src="/build/store-app-bundle.js"></script>
<script>System['import']('store/app');</script> // <--- error thrown here!!!
</body>
</html>
```

**Comment by guybedford** [comment]
Are you sure the exact line is that script? Perhaps try including the SystemJS polyfills in the page with a script tag here?

**Comment by tuurbo** [comment]
After looking at the error more, it fires 5x per page load and it first starts at ```<script src="/build/config.js"></script>```.

```
System.config({
//    ^ ReferenceError: Can't find variable: System
      baseURL: "/",
      defaultJSExtensions: true,
      ...
```

I'll manually include the polyfills before systemjs to see if the error stops.

**Comment by tuurbo** [comment]
Manually including the polyfills script didn't fix the issue.

**Comment by guybedford** [comment]
I'd suggest adding a console.log just before this line of SystemJS to check that it is being run - https://github.com/systemjs/systemjs/blob/master/dist/system-csp-production.src.js#L4318. And if not, to work back from there to see where execution is failing.

Perhaps also check if `window.SystemJS` is defined?

**Comment by tuurbo** [comment]
It's difficult to debug since I can't reproduce the error with my iPhone. But I did add the code below  which logs to the js tracking service I use, right after the systemjs script. The users that had the error also returned "SystemJS exists? false".

```
<script src="/build/systemjs.js"></script>
<script>trackJs.track('SystemJS exists? '+ (typeof window.SystemJS != 'undefined'));</script>
<script src="/build/config.js"></script>
```

**Comment by guybedford** [comment]
I think this may be something like http://stackoverflow.com/questions/4814217/woes-of-safaris-javascript-with-document-write. Perhaps try taking the script tag outside of the `</body>` tag. I really do think this is something that should have been resolved by including the system-polyfills.js before systemjs here.

As mentioned, tracing through those exact code lines linked in my previous comment would be the way to help here, as that's what I'd do on an isolated case if I had one to work with.

**Comment by guybedford** [comment]
If you include the promise polyfill itself with a script tag, and use the next release of SystemJS which includes https://github.com/systemjs/systemjs/issues/1070, I expect you'll find that resolves this.

**Comment by tuurbo** [comment]
Did as you said. Some users are still getting the error.

Useragent from one of the users. ```Mozilla/5.0 (iPhone; CPU iPhone OS 9_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13E233 Safari/601.1```

**Comment by guybedford** [comment]
@tuurbo if including a Promise polyfill and using SystemJS 0.19.25, then the only reason System would not be defined would be due to a synchronous script error executing SystemJS. Is there any way you can see if you can track down such a script error?

**Comment by tuurbo** [comment]
I can't reproduce the error myself, so I've given up on this for now

**Comment by zeeshanjan82** [comment]
I am facing exactly the same issue on safari however everything works fine on google chrome. Any suggestions?

**Comment by dottodot** [comment]
Same here . Works in chrome but not Safari on Mac and ios

**Comment by guybedford** [comment]
@zeeshanjan82 @dottodot if you can confirm you're running the latest SystemJS and including a Promise polyfill first and getting a bug here, please do share further details.

**Comment by tuurbo** [comment]
@guybedford I ended up switching to webpack :( to see if i had the same issue and i'm still seeing a lot of systemjs errors ```Can't find variable: System``` coming in from Safari mobile users and i'm positive systemjs is not being used anywhere on the site. I'm wondering if this has something to do with caching (forward/back caching) on Safari. Another words, the user went to our site, minimized safari, then later opened safari and navigated forward or back and safari tried to fetch old build files that no longer exist...

The build files have hashes append after the filename, eg: ```/build/systemjs.abcd1234.js```
```
// contains system-csp-production.js
<script src="/build/systemjs.{hash}.js"></script>
// contains config.js
<script src="/build/config.{hash}.js"></script>
// contains vendor scripts
<script src="/build/store-shared-bundle.{hash}.js"></script>
// contains app script
<script src="/build/store-app-bundle.{hash}.js"></script>
<script>System['import']('store/app');</script>
</body>
</html>
```
