### ISSUE TITLE
IE9 and IE10 reports multiple anonymous registers

### ISSUE THREAD

**Issue by Zenorbi** [systemjs/systemjs#799]
The attached test-app shows the bug described here.

https://github.com/Zenorbi/systemjs-ie-issue

To run the test:
```bash
npm install
node_modules/.bin/gulp serve
```
Steps to reproduce:
- Open the project in IE9 or IE10 (emulated IE's also show the bug).
- Open the console.
- Disable caching.
- Try refreshing the page until an exception happens (should show the bug within 5 refreshes).

console.log to show the position of the bug:
- open jspm_packages/system.src.js
- go to line 2436 `function doRegister(loader, name, register) {` and insert `console.log("doRegister called")`
- go to line 2352 `function complete(evt) {` and insert `console.log(s.readyState, s.src)`

Now, when you get an exception it shows that two files load simultaneously and then both execute `System.register` causing SystemJS to think it has 2 anonymous registers (and also missing the first script's register).

In IE, there is a special `readyState` for script tags called `"interactive"`. Interactive means the script is loaded and it's currently under the first execution. SystemJS should keep and array of currently loading modules and whenever `doRegister` is called, it should look for that `readyState`. RequireJS does this to avoid the bug.

From RequireJS:
```
//Probably IE. IE (at least 6-8) do not fire
//script onload right after executing the script, so
//we cannot tie the anonymous define call to a name.
//However, IE reports the script as being in 'interactive'
//readyState at the time of the define call.
```

**Comment by guybedford** [comment]
Thank you @Zenorbi for the detailed explanation here - I always wondered what all this fuss was about... now I know!

Ok, I think this should be relatively straightforward, and there are some benefits like being able to indicate which module is causing the `Multiple anonymous register` type errors etc.

Will aim to get a patch in asap.

@OliverJAsh this may explain IE instability as bundle loads may have sporadically had load errors due to this in IE9 and 10.

**Comment by guybedford** [comment]
I'm so grateful for this. Fixed above I believe, release to follow shortly. Please let me know if you notice anything else at all!

**Comment by Zenorbi** [comment]
Thank you @guybedford very much for the quick reaction!

**Comment by guybedford** [comment]
Released in 0.19.1.

**Comment by Zenorbi** [comment]
Sadly this fix didn't quiet work. If you clone the test-app and just do a `jspm install`, it should update SystemJS to 0.19.1. If you load the project up again in IE (9 or 10) and then start refreshing the page, eventually, around 15 retries, you'll get an exception.
"Unable to get property 'split' of undefined or null reference system.src.js (1459, 3)"

**Comment by Zenorbi** [comment]
If I remove the `meta` from `config.js` the bug never occurs. To quickly test wether it works or not, I recommend adding `location.reload(true);` after the `new Foobar.Foobar();` in `index.html`. Make sure you disable caches. For another project we're working on, removing the `meta` didn't fix it, it says:

```
Potentially unhandled rejection [2] TypeError: Unable to get property 'metadata' of undefined or null reference
  at Anonymous function (http://localhost:8080/static/commons/components/system/system.src.js:3679:9)
  at Anonymous function (http://localhost:8080/static/commons/components/system/system.src.js:2387:9)
  at define (http://localhost:8080/static/commons/components/system/system.src.js:3665:7)
  at Anonymous function (Unknown script code:1:19993)
  at o (Unknown script code:1:8518)
  at e (Unknown script code:1:8693)
  at execute (Unknown script code:1:8278)
  at ensureEvaluated (http://localhost:8080/static/commons/components/system/system.src.js:2950:5)
  at ensureEvaluated (http://localhost:8080/static/commons/components/system/system.src.js:2942:11)
  at ensureEvaluated (http://localhost:8080/static/commons/components/system/system.src.js:2942:11)
```

The project also has 0.19.1. I cannot share the code of this with you. If you have no idea about the second issue, we might be able to track it down for you in the big project and provide help that way.

**Comment by guybedford** [comment]
@Zenorbi thanks again, I've fixed this up in https://github.com/systemjs/systemjs/commit/4aa9bb694630c43d888e64d430a7462d3ed86931. Will post a release now.

**Comment by Zenorbi** [comment]
@guybedford Thank you very much for the support, the new release works smoothly. It's just amazing how quickly you react and how closely you provide info about the progress of the issue. I'm happy to be a user of SystemJS.

**Comment by guybedford** [comment]
Sure, no problem at all, this was a critical one so thanks for helping to isolate and understand it!

**Comment by OliverJAsh** [comment]
Here are the results from yesterday:

1.84% less in JspmTest. IE 9/10 still have the biggest in percent difference.

![image](https://cloud.githubusercontent.com/assets/921609/10197417/68be409c-678f-11e5-8ee3-b2c623801153.png)
