### ISSUE TITLE
Uncaught TypeError: Unexpected anonymous System.register call.

### ISSUE THREAD

**Issue by zeeshanjan82** [systemjs/systemjs#861]
I am using Systemjs and angularjs and whenever I load my application which is also using jspm I get this error in the console.

**Comment by guybedford** [comment]
@zeeshanjan82 can you share a test case here at all, or isolate the issue?

**Comment by zeeshanjan82** [comment]
@guybedford It will take me some time to isolate the issue and provide some more details. I will revert back in couple of days.

**Comment by smcmurray** [comment]
I've seen this when I import .html files and have
System.config.meta["*.html"].loader =="text"
&&
System.config.map["text"] =="github:systemjs/plugin-text@0.0.2"

importing from .html! files resolves the errors

**Comment by smcmurray** [comment]
I'm getting similar errors and having a hard time isolating them.

In my html, I have

````
<script type="text/javascript" src="/lib/system.js"></script>
<script type="text/javascript" src="/config.js"></script>
<script type="text/javascript">System.import('./app.js')</script>
````

And inside ./app.js I have
````
import a from 'a';
import b from 'b';
import c from 'c';
````

The error jumps erratically around, sometimes pointing at b, sometimes at c. I can't nail down a testcase.

**Comment by lyptt** [comment]
This is also happening for me, but only in Firefox. Chrome/Safari/IE11 seem to be unaffected. The issue seems to disappear on FF Dev Edition

**Comment by guybedford** [comment]
@lyptt are you sure you are running the latest version of SystemJS?

**Comment by lyptt** [comment]
@guybedford I should be yes, I'm on SystemJS 0.19.5 according to my jspm_packages.

**Comment by guybedford** [comment]
@lyptt sure, is there anyway you can share a reproducible case for this?

**Comment by lyptt** [comment]
@guybedford I'll definitely give it a go. The project I found the issue on is a bit complex so I'll have to come up with something a bit simpler

**Comment by guybedford** [comment]
Thanks, would be appreciated.

**Comment by smcmurray** [comment]
I'm grasping at straws a bit here, but I have this problem in conjuction with issue #873. Trying to track down that issue, the browser points me to an anonymous function call in system.src.js:4573.

In the version I am running (0.19.5 Standard), line 4573 is:
`bootstrap();`

I'm confused at how I reach line 4573 because it is guarded by the if clause:
`if (typeof Promise === 'undefined' || !hasURL)`
In my browser (Chrome 45.0.2454.101 (64-bit)), Promise is a function and new URL('test:///').protocol == 'test:'

**Comment by jmathai** [comment]
@smcmurray which version of Firefox are you on? Using a version < 41.0.2 didn't come across this but we have two people that started to get this error once Firefox upgraded to 41.0.2. Not sure if that's a culprit but seems suspicious.

**Comment by smcmurray** [comment]
@jmathai, the report above is using Chrome 45.0.2454.101 (64-bit)

**Comment by smcmurray** [comment]
@jmathai, similar results in Firefox 41.0

**Comment by guybedford** [comment]
If you're getting this issue, can you try adding this configuration to SystemJS:

```javascript
System.config({ globalEvaluationScope: false })
```

And let me know if that helps?

**Comment by smcmurray** [comment]
@guybedford same results with globalEvaluationScope: false

**Comment by guybedford** [comment]
I guess help replicating would be the way forward then.

**Comment by justinwoodcock** [comment]
I'm able to reproduce in firefox v41.0.2 by simply installing and enabling firebug, can anyone confirm? Will test the globalEvaluationScope fix and report back. @guybedford @jmathai @smcmurray

**Comment by guybedford** [comment]
@justinwoodcock thanks, this is a Firebug issue, which I've posted in https://github.com/systemjs/systemjs/issues/878. There are of course many other reasons this message can appear, including user error though.

**Comment by olanod** [comment]
I'm getting this error but is not related to firefox. I get it with the karma preprocessor and the jade plugin.

**Comment by monokrome** [comment]
I'm getting it in Chrome

**Comment by SerkanSipahi** [comment]
@guybedford get the same error but with karma see repo: https://github.com/SerkanSipahi/app-decorators

`System.config({ globalEvaluationScope: false })` has no effect !

```
git clone https://github.com/SerkanSipahi/app-decorators.git
cd app-decorators
npm install
node_modules/.bin/karma start

Firefox 41.0.0 (Mac OS X 10.11.0) ERROR
  TypeError: Unexpected anonymous System.register call.
  at app-decorators/node_modules/systemjs/dist/system.src.js:2692

Chrome 46.0.2490 (Mac OS X 10.11.0) ERROR
  Uncaught TypeError: Unexpected anonymous System.register call.
  at app-decorators/node_modules/systemjs/dist/system.src.js:2692

**Comment by frapontillo** [comment]
I am having the exact same issue as @SerkanSipahi but by running karma on PhantomJS.
The full output is:
```
PhantomJS 1.9.8 (Mac OS X 0.0.0) ERROR
  TypeError: Unexpected anonymous System.register call.
  at bower_components/system.js/dist/system.src.js:2692
```

The injected files in Karma are:
```
[ 'bower_components/system.js/dist/system-polyfills.src.js',
  'bower_components/system.js/dist/system.src.js',
  'bower_components/angular/angular.js',
  'bower_components/angular-mocks/angular-mocks.js',
  '.tmp/my-compiled-library.js',
  'src/**/*.html' ]
```

**Comment by SerkanSipahi** [comment]
@frapontillo i switched to https://github.com/Workiva/karma-jspm , this works fine for me. See my working state: https://github.com/SerkanSipahi/app-decorators ( master branch or tag test.karma.jspm )

**Comment by jimschubert** [comment]
Another way this error can occur is if you pass your `System.config` registration through a transpiler with incompatible settings (e.g. babel with the `modules='system'` option).

This will result in something like:

```js
System.register([], function (_export) {
  "use strict";

  return {
    setters: [],
    execute: function () {
      System.config({
      });
    }
  };
});
```

Which will get you the error. Don't run `config.js` or whatever through your transpiler and if this is one of the scenarios resulting in the error, it should start working.

**Comment by tbragaf** [comment]
Is it possible you are using a config.js?

Can you remove config.js and place it inside a script in index.html?
Also, can you try to export config.js as a module?

My config.js looked like this:
```js 
System.register([], function($__export) {
  "use strict";
  return {
    setters: [],
    execute: function() {
      System.config({map: {'traceur-runtime': '../node_modules/gulp-traceur/node_modules/traceur/bin/traceur-runtime.js'}});
      System.import('bootstrap.js').catch(function(response) {
        console.error(response);
      });
    }
  };
});
´´´

So, the error is true, the module has no name, it is an anonymous module.
Does this help?

Best regards,
tbragaf

**Comment by monokrome** [comment]
My repo (linked above) has the same issue that @tbragaf has just posted. There is no config.js on my machine. Is the comment in https://github.com/systemjs/systemjs/issues/861#issuecomment-158819228  possible explanation of this issue?

**Comment by jimschubert** [comment]
@monokrome I don't see systemjs in your repo. Did you link to the right thing?

**Comment by tbragaf** [comment]
@monokrome 
As @jimschubert  mentioned, you shouldn't transpile the config.js
Please provide your repo so we can take a look :)

**Comment by monokrome** [comment]
@tbragaf I linked the repo above, it's [here][link]. I don't know if it's helpful or not, and what I was saying is that there isn't a `config.js`.

[link]: https://github.com/monokrome/monokro.me/tree/wtf-is-going-on.

**Comment by jithin1987** [comment]
I am seeing this error on Firefox, not on Chrome though. And restarting FF makes this go away for a while.

**Comment by tbragaf** [comment]
@monokrome Oh I see, you are using concat to add systemjs. Sorry, but I couldn't run the branch.
You shouldn't transpile the systemjs right?
I am not sure, but you are adding systemjs to src and then transpiling? Is that correct? I am not a big gulp user, sorry.

**Comment by justin-schroeder** [comment]
I'm also seeing this error on Firefox (40.0.3) and firefox only. I've tried numerous configurations, two things that stood out in all this:

- Exception is thrown on any ES6 import statements, when using babel for realtime transpiling. No exceptions are thrown when compiling ahead of time and only loading ES5.
- I had a reference to an undefined variable in my code (oddly, in a scope which wasn't even being executed), thus I assumed it was completely unrelated, but when I corrected it, the all `TypeError: Unexpected anonymous System.register call.` exceptions went away.

Could this somehow be babel choking on minor js bugs in the transpiling process?

**Comment by guybedford** [comment]
@justin-schroeder is this with Firebug running or not?

**Comment by mnichols** [comment]
I am running FF 42.0 on OSX and can confirm that adding `globalEvaluationScope: false` to my `config.js` made the error go away. I am not running Firebug.

**Comment by guybedford** [comment]
@mnichols thanks for the update... I'm hoping to make that the default in future.

**Comment by unional** [comment]
Seems like I still encounter this issue, with `globalEvaluationScope: false`.
When Firebug is not running, It have this warning instead: `unreachable code after return statement` when I open Firebug to check.

Here is the repo:
https://github.com/coolcodeexamples/timely-wealth-game

**Comment by guybedford** [comment]
@unional try disabling Firebug entirely?

**Comment by unional** [comment]
I re-test it and somehow it is working now. With and without firebug. 

And I noticed I actually don't have firebug installed in that environment. Just the basic dev-tool.
I have verified it is working on all counts: w/wo dev-tool opened (i.e. firebug not present or disabled), w/wo firebug opened.

For reference:
* jspm 0.16.25
* ts 2.5.5

**Comment by m0ru** [comment]
I'm experiencing similiar sounding problems on firefox 43.0 (windows) with jspm 0.16.27. 

* [startup-console](https://gist.github.com/m0ru/c5c69cb77497d6c7954a)
* [startup-console with `globalEvaluationScope: false`](https://gist.github.com/m0ru/be779b0083e184ef7a49)
* [app.js](https://github.com/researchstudio-sat/webofneeds/blob/feat-feed/webofneeds/won-owner-webapp/src/main/webapp/app/app_jspm.js) (sorry for the franken-code ^^")
* [jspm_config.js](https://github.com/researchstudio-sat/webofneeds/blob/feat-feed/webofneeds/won-owner-webapp/src/main/webapp/jspm_config.js)
* [package.json](https://github.com/researchstudio-sat/webofneeds/blob/feat-feed/webofneeds/won-owner-webapp/src/main/webapp/package.json)
* [index.html](https://github.com/researchstudio-sat/webofneeds/blob/feat-feed/webofneeds/won-owner-webapp/src/main/webapp/rework.html)

When i change the order of the includes in the app.js, different files trigger the error. However I haven't managed to track down the specific import at fault yet. (It's not the first import though, which suggests that it's a specific import, doesn't it?)

**Comment by monokrome** [comment]
@tbragaf Not sure if this is still helpful, but - as a response to your previous question - the `tsFilter` pipe only lets TypeScript files through, so SystemJS won't be transpiled in my example. It'll be concatenated into the beginning of the file, and then the ts files will be afterward.

**Comment by djindjic** [comment]
also have same issue by running karma jasmin tests in typesctipt "visual studio" project without jspm

**Comment by djindjic** [comment]
I've fixed it by using System.import instead of es6 import statement for unit test dependencies.

**Comment by Luixo** [comment]
Opening debugger triggers cache-related problem: loading fails on libs with AMD support (react, underscore) with error: _AMD module file:///C:/path_to_libs/underscore.js did not define_
Setup:
- Firefox 41.0.2
- SystemJS v0.19.23
- Modules are transpiled from import/export syntax by babel plugin

**Comment by m0ru** [comment]
It might be related to the dynamic compiling. When I run the exact same setup as mentioned above but loading a bundled app instead, the error is gone.

**Comment by Luixo** [comment]
Seems like adding map for library in config somehow solves the problem.

**Comment by Luixo** [comment]
Temporarily fixed this problem, but very strange way. I have a plugin that override fetch method for loading and try to grab file from several paths (prepared path is formed in overriden locate method). When i add some guranteed failed path for load, fetching takes more time than usual and in 9 from 10 cases i can use debugger safely. Example plugin code:
```
Promise.reduce = (fns, val) => fns.reduce((prev, current) => prev.then(result => current(result)), val instanceof Promise ? val : Promise.resolve(val));
exports.locate = load => {
	try {
		let customPath = load.name;
		return `file:///C:/fail.txt|${customPath }`;
	}
	catch (e) { return load.name; }
};
exports.fetch = (load, loader) => {
	let paths = load.address.split('|');
	return Promise.reduce(paths.map((_, index) =>
			() => Promise.resolve(load.address = paths[index])
				.then(() => loader(load))
				.then(loadedFile => Promise.reject(loadedFile), failed => Promise.resolve(failed))
	))
		.then(err => Promise.reject(`Failed to load files on: ${paths.join('; ')}, sample error: ${err}`), loadedFile => Promise.resolve(loadedFile))
};
```
Hope developers that know systemjs code better than me could reproduce and locate the problem.

**Comment by alexkmbk** [comment]
I'm getting this error in very simple example and asked a question in stackoverflow:
http://stackoverflow.com/questions/36176523/javascript-error-unexpected-anonymous-system-register-call

No answer :-(

**Comment by geea789** [comment]
for me its actually because the load sent to 
hook('reduceRegister_', function() {
is null.

this is the full stack trace
Error: Unexpected anonymous System.register call.
	Evaluating http://localhost:9000/dist/auth-config.js
	Error loading http://localhost:9000/dist/auth-config.js as "auth-config" from http://localhost:9000/dist/main.js
Stack trace:
"bootstrap/</</</<@http://localhost:9000/jspm_packages/system.src.js:2681:1bootstrap/</</<@http://localhost:9000/jspm_packages/system.src.js:3221:1bootstrap/</</</</<@http://localhost:9000/jspm_packages/system.src.js:3750:1bootstrap/</</</<@http://localhost:9000/jspm_packages/system.src.js:2411:9bootstrap/</</SystemJSLoader.prototype.register@http://localhost:9000/jspm_packages/system.src.js:2636:1anonymous/<@http://localhost:9000/dist/auth-config.js:1:20anonymous@http://localhost:9000/dist/auth-config.js:1:1evalExec@http://localhost:9000/jspm_packages/system.src.js:1338:7bootstrap/</</__exec@http://localhost:9000/jspm_packages/system.src.js:1355:1bootstrap/</</</<@http://localhost:9000/jspm_packages/system.src.js:3054:11bootstrap/</</<@http://localhost:9000/jspm_packages/system.src.js:3306:12bootstrap/</</</<@http://localhost:9000/jspm_packages/system.src.js:3567:14bootstrap/</</</<@http://localhost:9000/jspm_packages/system.src.js:3872:14bootstrap/</</</<@http://localhost:9000/jspm_packages/system.src.js:4086:16proceedToTranslate/</<@http://localhost:9000/jspm_packages/system.src.js:346:16"

**Comment by phicho** [comment]
The error was happening for me because i was loading the js files from a script tag and also through systemjs.
